--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: beach; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.beach (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    image_path character varying(255),
    latitude double precision,
    location character varying(255) NOT NULL,
    longitude double precision,
    name character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    water_type character varying(255) NOT NULL,
    CONSTRAINT beach_water_type_check CHECK (((water_type)::text = ANY (ARRAY[('FRESHWATER'::character varying)::text, ('SALTWATER'::character varying)::text])))
);


ALTER TABLE public.beach OWNER TO postgres;

--
-- Name: beach_fish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.beach_fish (
    id bigint NOT NULL,
    beach_id bigint NOT NULL,
    fish_id bigint NOT NULL
);


ALTER TABLE public.beach_fish OWNER TO postgres;

--
-- Name: beach_fish_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.beach_fish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beach_fish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: beach_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.beach ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fish (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.fish OWNER TO postgres;

--
-- Name: fish_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_reset_log (
    id bigint NOT NULL,
    ip_address character varying(255),
    is_successful boolean,
    request_time timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_log OWNER TO postgres;

--
-- Name: password_reset_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_reset_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    is_active boolean NOT NULL,
    password character varying(100) NOT NULL,
    phone_number character varying(255),
    role character varying(20) NOT NULL,
    username character varying(50) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: beach; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.beach (id, approved, created_at, description, image_path, latitude, location, longitude, name, updated_at, water_type) FROM stdin;
24	t	2025-01-25 18:06:52.58045	A beautiful small beach with calm waters and historical surroundings.	beaches/1737825847202_caleta.jpeg	36.5336	Cádiz	-6.2994	Playa de la Caleta	2025-01-25 18:24:07.220815	SALTWATER
25	t	2025-01-25 18:08:01.792721	A popular city beach with modern facilities and restaurants.	beaches/1737825879181_malagueta.jpeg	36.7194	Málaga	-4.4143	Playa de la Malagueta	2025-01-25 18:24:39.188855	SALTWATER
26	t	2025-01-25 18:08:56.500697	A pristine beach known for its crystal-clear waters and unique rock formations.	beaches/1737825898188_muertos.jpeg	36.9631	Almería	-1.8955	Playa de los Muertos	2025-01-25 18:24:58.196012	SALTWATER
27	t	2025-01-25 18:10:10.288944	A picturesque beach famous for its sand dunes and archaeological sites.	beaches/1737825916241_bolonia.jpeg	36.0881	Tarifa	-5.7745	Playa de Bolonia	2025-01-25 18:25:16.248954	SALTWATER
37	t	2025-01-26 19:40:28.861499	A long beach with modern facilities, ideal for fishing anchovy and mackerel.	beaches/1737827001006_motril.jpeg	36.7376	Motril	-3.5304	Playa de Motril	2025-01-26 19:40:28.861499	SALTWATER
32	t	2025-01-26 19:38:31.946624	A picturesque reservoir nestled in the Sierra Nevada mountains, ideal for fishing trout and carp.	beaches/1737827001001_canales.jpeg	37.1499	Güéjar Sierra	-3.4891	Embalse de Canales	2025-01-26 19:38:31.946624	FRESHWATER
33	t	2025-01-26 19:39:40.804498	A quiet reservoir near Granada, popular for fishing carp and perch.	beaches/1737827001002_cubillas.jpeg	37.2833	Albolote	-3.6167	Pantano de Cubillas	2025-01-26 19:39:40.804498	FRESHWATER
34	t	2025-01-26 19:39:57.428702	A stunning reservoir in the Lecrín Valley, surrounded by lush greenery, perfect for fishing carp and perch.	beaches/1737827001003_beznar.jpeg	36.9167	Lecrín Valley	-3.5333	Embalse de Béznar	2025-01-26 19:39:57.428702	FRESHWATER
35	t	2025-01-26 19:40:06.33301	A modern reservoir on the way to Costa Tropical, ideal for fishing perch and sander.	beaches/1737827001004_rules.jpeg	36.8085	Vélez de Benaudalla	-3.4783	Embalse de Rules	2025-01-26 19:40:06.33301	FRESHWATER
36	t	2025-01-26 19:40:18.457345	A scenic beach on the tropical coast, perfect for fishing dorado and sea bass.	beaches/1737827001005_herradura.jpeg	36.7354	La Herradura	-3.7327	Playa de La Herradura	2025-01-26 19:40:18.457345	SALTWATER
38	t	2025-01-26 19:40:40.92928	A picturesque beach with views of the Salobreña castle, perfect for fishing barracuda and snapper.	beaches/1737827001007_salobrena.jpeg	36.7355	Salobreña	-3.592	Playa de Salobreña	2025-01-26 19:40:40.92928	SALTWATER
31	t	2025-01-26 14:49:15.736075	A tranquil reservoir surrounded by pine forests, popular for fishing carp, catfish, and perch.	beaches/Embalse_de_la_Brea_1738086060200.jpeg	37.811	Almodóvar del Río	-5.0297	Embalse de La Breña	2025-01-28 18:41:00.209605	FRESHWATER
30	t	2025-01-26 14:48:53.151564	A serene lake within a natural park, ideal for trout and bass fishing amidst breathtaking nature.	beaches/Embalse_del_Tranco_1738086105254.jpeg	38.0806	Sierra de Cazorla	-2.9023	Embalse del Tranco	2025-01-28 18:41:45.263761	FRESHWATER
29	t	2025-01-26 14:48:24.792135	The largest reservoir in Andalusia with beautiful beaches, perfect for fishing carp, barbel, and catfish.	beaches/Embalse_de_Iznjar_1738086121447.jpeg	37.2664	Iznájar	-4.3071	Embalse de Iznájar	2025-01-28 18:42:01.454986	FRESHWATER
28	t	2025-01-26 14:47:46.862954	A picturesque reservoir surrounded by mountains, ideal for fishing carp, bass, and trout.	beaches/Embalse_de_Zahara-El_Gastor_1738086137554.jpeg	36.839	Zahara de la Sierra	-5.4136	Embalse de Zahara-El Gastor	2025-01-28 18:42:17.56228	FRESHWATER
39	f	2025-04-22 11:52:06.855622	string	string	0	string	0	string	2025-04-22 11:52:06.855622	SALTWATER
\.


--
-- Data for Name: beach_fish; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.beach_fish (id, beach_id, fish_id) FROM stdin;
\.


--
-- Data for Name: fish; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fish (id, approved, created_at, name, updated_at) FROM stdin;
\.


--
-- Data for Name: password_reset_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_reset_log (id, ip_address, is_successful, request_time, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, is_active, password, phone_number, role, username) FROM stdin;
1	testuser@example.com	t	$2a$10$vxluyoplJBgNOZeYmJIerO4SRNAB3/VWMQf.hsoIo7trv/KoyCtti	+1234567890	USER	testuser
3	testuser@example1.com	t	$2a$10$SHwUPAUXpOEBwIzEHe9e.u8wHvQWkXmP9lhiPLHzAqleM2YqnYMjq	+12345678901	USER	testuser1
6	testuser@example11.com	t	$2a$10$f1XASNEE3RvdTLWRyJpz/OCQ00kSjnYd.DtkpE4YKlF4VLdvGI4kW	+123456789011	USER	testuser11
9	testuser@exampl.com	t	$2a$10$3DO6v0VD/RdG4Qe8yiaLkOmZgeXA3FBdo3tjFZbez9ohEKEKXXmE2	+12345678000	USER	testuse
18	test@example.com	t	$2a$10$MYcObgLj9mROmC9aRxCPGO5KTmg.on5YaLeuQwfiQ21H37Awd7ldy	+1234567891	USER	tes
21	testtttttttt1@example.com	t	$2a$10$nAzvUPSrWki0wTKJd/YVuua1JvKzQAIMzn0/LvdwA072L.dp1I.w2	+1234567892	USER	testtttttttttt1
24	testtttttt1@example.com	t	$2a$10$brpArP4/1JmP..g5QP6Eu.j1./BhmzQIjQ4g600D8n7Ix32FC1r6K	+1234567893	USER	testtttttttt1
26	testttttt1@example.com	t	$2a$10$chSY3zqtEL7EO/UmBQI1/.ZzF838SkmX84obk6wnmNJb9TR7J5UlS	+1234567894	USER	testttttttt1
27	testtttt1@example.com	t	$2a$10$t9iUpFmnW5vQeuCsxTASgOFP0qO/9WC7rArVDWLdQY4dIwHQC0WIG	+1234567899	USER	testtttttt1
28	testtt1@example.com	t	$2a$10$J4ET7CCPnSuOVFi2t8.pReENBWVgz5E8xXPznZr804u7.TKXIhqxO	+1234444568	USER	testtttt1
29	testt1@example.com	t	$2a$10$48OaBaATwQDypFs4DErY6.uDn4x33dhPVmKAqSKpDTT.vp85CSHPe	1234567890	USER	testttt1
30	tessssssssssst@example.com	t	$2a$10$BLouTk150ofrrnVrJ6PuUOzePw73lhr6dCsHB6xHvKVF1vFARWWAm	+123456789999	USER	tessssssssssst
31	tesssssssssst@example.com	t	$2a$10$oEim3Y9ZaSYHofBSET5O/uj.VDsiTcZcJ44PUWcBVkIUGa9FN9tDq	+12345678999	USER	tesssssssssst
32	admin@example.com	t	$2a$10$hjaxuzhhDUBXw1Hqv./GcOqX3uUgQsi8INSxQZR/jB2BxPLTArfFe	+12345670000	ADMIN	admin
33	admin1@example.com	t	$2a$10$4vekq2Xb/E51caucwvUVuu1FEpS1p9vjsgmdIFUQAzQ/MTO5rUuGy	+112345670000	USER	admin1
34	arturo.sultanov@gmail.com	t	$2a$10$zqij2rGi1YpC/xnNoCMDMOOSuUBR4vBKY0BX5d21DHuJOMDrvem6W	+345670000000	USER	admin2
35	arturo.sultanov1985@gmail.com	f	$2a$10$/9BfNpns9B6si3NJvjLssepiR7Qpr9dVdOrMqanAcCqmL9jPDoFFW	+3456700000000	ADMIN	admin3
\.


--
-- Name: beach_fish_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.beach_fish_id_seq', 1, false);


--
-- Name: beach_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.beach_id_seq', 39, true);


--
-- Name: fish_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fish_id_seq', 1, false);


--
-- Name: password_reset_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_reset_log_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 35, true);


--
-- Name: beach_fish beach_fish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach_fish
    ADD CONSTRAINT beach_fish_pkey PRIMARY KEY (id);


--
-- Name: beach beach_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach
    ADD CONSTRAINT beach_pkey PRIMARY KEY (id);


--
-- Name: fish fish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fish
    ADD CONSTRAINT fish_pkey PRIMARY KEY (id);


--
-- Name: password_reset_log password_reset_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_reset_log
    ADD CONSTRAINT password_reset_log_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: fish ukfa81c7mr3er8so9g9lwpjwwj0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fish
    ADD CONSTRAINT ukfa81c7mr3er8so9g9lwpjwwj0 UNIQUE (name);


--
-- Name: beach ukl8vaih81dqfe4ak8gyw6qwyub; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach
    ADD CONSTRAINT ukl8vaih81dqfe4ak8gyw6qwyub UNIQUE (name, location);


--
-- Name: beach ukmkx6de7dyvoeqvxt1isguy18l; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach
    ADD CONSTRAINT ukmkx6de7dyvoeqvxt1isguy18l UNIQUE (image_path);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_beach_location; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_beach_location ON public.beach USING btree (location);


--
-- Name: idx_beach_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_beach_name ON public.beach USING btree (name);


--
-- Name: beach_fish fk3jcxofa16rnkcxqch9bd7w3ek; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach_fish
    ADD CONSTRAINT fk3jcxofa16rnkcxqch9bd7w3ek FOREIGN KEY (beach_id) REFERENCES public.beach(id);


--
-- Name: beach_fish fkp7qs2pny6s1f7ttjshmiqd14p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beach_fish
    ADD CONSTRAINT fkp7qs2pny6s1f7ttjshmiqd14p FOREIGN KEY (fish_id) REFERENCES public.fish(id);


--
-- PostgreSQL database dump complete
--

